### ISSUE TITLE
Crash after adding the notificationcenter

### ISSUE THREAD

**Issue by fo0** [KaesDingeling/Hybrid-Menu#38]
looks like you are not adding the notificationcenter after declaration

```
Caused by: java.lang.NullPointerException
	at com.vaadin.ui.AbstractComponentContainer.addComponent(AbstractComponentContainer.java:173)
	at com.vaadin.ui.AbstractOrderedLayout.addComponent(AbstractOrderedLayout.java:95)
	at kaesdingeling.hybridmenu.HybridMenu.build(HybridMenu.java:93)
	at kaesdingeling.hybridmenu.builder.HybridMenuBuilder.build(HybridMenuBuilder.java:42)
```

**Comment by KaesDingeling** [comment]
Is fixxed in Version 2.0.10
