### ISSUE TITLE
SpringBoot boot failed when read css content from File.

### ISSUE THREAD

**Issue by leotu** [KaesDingeling/Hybrid-Menu#56]
HybridMenu#fileToString(...)
Not working correctly when execution boot file like "xxx-exec.jar"
It is better to use 
"HybridMenu.class.getClassLoader().getResourceAsStream(fileName)" +
"new Scanner(InputStream)"

```java
xxx.jar!/css/hybridMenu.css (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.util.Scanner.<init>(Scanner.java:611)
```

**Comment by KaesDingeling** [comment]
The problem has already been solved. https://gitlab.com/KaesDingeling/Hybrid-Menu/issues/54

Please update the HybridMenu version to 3.0.11.vaadin10 or newer
